#!/usr/bin/env bash
# Regenerate .github/workflows/plugin-*-*.yml caller workflows from the list below.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/.github/workflows"

TARGETS=(
  "linux:amd64"
  "linux:arm"
  "linux:arm64"
  "windows:amd64"
  "windows:arm64"
  "darwin:arm64"
)

rows=(
  "vault-plugin-secrets-kafka:kafka"
  "vault-plugin-secrets-machine:machine"
  "vault-plugin-secrets-github:github"
)

for row in "${rows[@]}"; do
  plugin="${row%%:*}"
  short="${row#*:}"
  for spec in "${TARGETS[@]}"; do
    goos="${spec%%:*}"
    goarch="${spec#*:}"
    fname="plugin-${short}-${goos}-${goarch}.yml"
    fpath="$OUT/$fname"
    cat >"$fpath" <<EOF
# Generated by scripts/generate-plugin-ci-workflows.sh
name: "${short} ${goos}/${goarch}"

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - 'plugins/${plugin}/**'
      - '.github/workflows/reusable-plugin-build.yml'
      - '.github/workflows/${fname}'
  pull_request:
    paths:
      - 'plugins/${plugin}/**'
      - '.github/workflows/reusable-plugin-build.yml'
      - '.github/workflows/${fname}'

jobs:
  build:
    uses: ./.github/workflows/reusable-plugin-build.yml
    with:
      plugin: ${plugin}
      goos: ${goos}
      goarch: ${goarch}
EOF
    echo "wrote $fpath"
  done
done
